name: Check formatting

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:19.10

    steps:
    - name: apt-get update
      run: apt-get update

    - name: Install clang-format
      run: apt-get install clang-format

    - name: Check formatting
      run: ./tools/check-format.sh
