name: Check formatting

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Chatterino2 Docker check-format image
      run: docker build . --file .docker/Dockerfile.check-format --tag chatterino2-check-format

    - name: Check formatting
      run: ./tools/check-format.sh
